make sure I always build the opam files
Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -13,3 +13,9 @@ else
   echo >&2 "[ERR] Failed precommit validation: opam isn't available"
   exit 1
 fi
+
+# Code that checks if any file of the form *.opam has active diffs and exits with 1 if there is one
+if git diff --name-only | grep -qE '\.opam$'; then
+  echo >&2 "[ERR] Failed precommit validation: opam files have active diffs, probably triggered by the build steps"
+  exit 1
+fi
