Switch to opam (#293)
* switching to opam... step 1

* add gillian to deps

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* update opam file

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* flow_parser not flow

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* in dune-project

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* fix dependencies

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* add lock file and use init-ci instead of init-dev

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* add dune-site dep

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* add appropriate dependencies

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* fix ci

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* some more improvements to CI, not done yet

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* make sure I always build the opam files

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* another try at docker, plus slight ci improvement

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* ANOTHER ONE

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* Update Dockerfile

* pleeeassee

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* and yet more

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* fix + cache docker CI

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* tiny changes

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>

* Update dune version

* Collect minimum distributable files, update CI

* Tweak make init-ci

* Update ci.yml

* Try to find binaries in CI

* Trying something else

* Remove "opam exec -- dune exec --" from test scripts

* Tweak binary path in CI

* Set permissions on CI binaries

* make dist: use dune relocatable

* CI: try to load libz3

* Bump dune version

* Just use _opam as artifact 😪

* Update artifact action, fix setup-ocaml

* Compress artefact before uploading

* Attempt to fix opam env in CI

* More CI tweaks

* Include Gillian-JS runtime sites in import paths

* Fix docker CI?

* Fix docker CI??

* Fix docker CI???

---------

Signed-off-by: Sacha Ayoun <sachaayoun@gmail.com>
Co-authored-by: Nat Karmios <nat@karmios.com>

diff --git a/githooks/pre-commit b/githooks/pre-commit
--- a/githooks/pre-commit
+++ b/githooks/pre-commit
@@ -2,15 +2,20 @@
 
 set -euo pipefail
 
-if command -v esy >/dev/null 2>&1; then
+if command -v opam >/dev/null 2>&1; then
   echo "[INFO] Running source code formatting"
-  esy format-check
+  opam exec -- dune fmt
 
   echo "[INFO] Running build"
-  esy
-
+  opam exec -- dune build
   exit 0
 else
-  echo >&2 "[WARN] Failed precommit validation: esy isn't available"
+  echo >&2 "[ERR] Failed precommit validation: opam isn't available"
+  exit 1
+fi
+
+# Code that checks if any file of the form *.opam has active diffs and exits with 1 if there is one
+if git diff --name-only | grep -qE '\.opam$'; then
+  echo >&2 "[ERR] Failed precommit validation: opam files have active diffs, probably triggered by the build steps"
   exit 1
 fi
